---
# tasks file for replication

- name: ServerID setup
  ldap_attr:
    dn: cn=config
    name: olcServerID
    values: '{{server_id}}'
    state: exact

- name: Index reset to default
  ldap_attr:
    dn: olcDatabase={2}hdb,cn=config
    name: olcDbIndex
    values:
      - objectClass eq,pres
      - ou,cn,mail,surname,givenname eq,pres,sub
      - entryUUID  eq
      - entryCSN  eq
    state: exact

- name: Checking if olcSyncRepl destination exists in {2}hdb
  command: cat /etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif
  register: syncrepl_hdb_state

- name: Template for removing olcSyncRepl preparation from {2}hdb
  template:
    src: ~/ansible-ldap/roles/replication/templates/syncreplrmv_hdb.ldif
    dest: ~/syncreplrmv_hdb.ldif

- name: Removing olcSyncRepl if exists in {2}hdb
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f ~/syncreplrmv_hdb.ldif
  when: '"olcSyncrepl:" in syncrepl_hdb_state.stdout'


- name: olcSyncRepl exact
  ldap_attr:
    dn: olcDatabase={2}hdb,cn=config
    name: olcSyncRepl
    values:
#      - rid=001 provider=ldap://ldap0.{{domain}}.{{suffix}}:389/ bindmethod=simple binddn="cn={{admin_account}},dc={{domain}},dc={{suffix}}" credentials=xxxxxx searchbase="dc={{domain}},dc={{suffix}}" scope=sub schemachecking=on type=refreshAndPersist interval=00:00:05:00
       - >-
         rid=001
         provider=ldap://ldap0.{{domain}}.{{suffix}}:389/
         bindmethod=simple
         binddn="cn={{admin_account}},dc={{domain}},dc={{suffix}}"
         credentials=xxxxxx
         searchbase="dc={{domain}},dc={{suffix}}"
         scope=sub
         schemachecking=on
         type=refreshAndPersist
         interval=00:00:05:00
       - >-
         rid=002
         provider=ldap://ldap1.{{domain}}.{{suffix}}:389/
         bindmethod=simple
         binddn="cn={{admin_account}},dc={{domain}},dc={{suffix}}"
         credentials=xxxxxx
         searchbase="dc={{domain}},dc={{suffix}}"
         scope=sub
         schemachecking=on
         type=refreshAndPersist
         interval=00:00:05:00
    state: exact

- name: olcMirrormode exact
  ldap_attr:
    dn: olcDatabase={2}hdb,cn=config
    name: olcMirrorMode
    values: 'TRUE'
    state: exact

