---
# tasks file for replication

- name: ServerID template
  template:
    src: ~/ansible-ldap/roles/replication/templates/serverid.ldif
    dest: ~/serverid.ldif

- name: ServerID define
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f ~/serverid.ldif

- name: Checking if olcSyncRepl destination exists in {2}hdb
  command: cat /etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif
  register: syncrepl_hdb_state

- name: Template for removing olcSyncRepl preparation from {2}hdb
  template:
    src: ~/ansible-ldap/roles/replication/templates/syncreplrmv_hdb.ldif
    dest: ~/syncreplrmv_hdb.ldif
#  when: '"olcSyncrepl:" in syncrepl_hdb_state.stdout'

- name: Removing olcSyncRepl if exists in {2}hdb
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f ~/syncreplrmv_hdb.ldif
  when: '"olcSyncrepl:" in syncrepl_hdb_state.stdout'

- name: Checking if other index exists
  command: grep olcDbIndex /etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif 
  register: other_index

- name: Index reset to default
  ldap_attr:
    dn: olcDatabase={2}hdb,cn=config
    name: olcDbIndex
    values:
      - objectClass eq,pres
      - ou,cn,mail,surname,givenname eq,pres,sub
    state: exact
  when: '"entryUUID" in other_index.stdout'

- name: Template for olcdatabasehdb preparing
  template:
    src: ~/ansible-ldap/roles/replication/templates/olcdatabasehdb.ldif
    dest: ~/olcdatabasehdb.ldif

- name: Updating {2}hdb
  command: ldapmodify -Y EXTERNAL -H ldapi:///  -f ~/olcdatabasehdb.ldif

