---
# tasks file for install
- name: Install required software
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - openldap
    - openldap-clients
    - openldap-servers
    - python-ldap
    - compat-openldap
    - openldap-devel

- name: Service slapd enable
  command: systemctl {{item}} slapd
  with_items:
   - enable
   - restart
  notify:
   - restart slapd

- name: Checking if DB_config exists
  stat:
    path: /var/lib/ldap/DB_CONFIG 
  register: dbconfig

- name: SampleDB config copy
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example 
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: yes
  when: dbconfig.stat.exists == False

- name: Permission update
  file: 
    path: /var/lib/ldap/
    owner: ldap
    group: ldap 

#- name: LOGs enable
#  shell:
#    sudo echo "local4.* /var/log/ldap.log" >> /etc/rsyslog.conf
#    systemctl restart rsyslog
#  when: '"local4.* /var/log/ldap.log" not in /etc/rsyslog.conf'
